CREATE TABLE IF NOT EXISTS login (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(32) NOT NULL,
  email VARCHAR(32) NOT NULL,
  password VARCHAR(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS results (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sportName VARCHAR(32) NOT NULL,
  league VARCHAR(32) NULL,
  championship VARCHAR(32) NULL,
  grandPrix VARCHAR(32) NULL,
  matchDate DATE NULL,
  raceDate DATE NULL,
  driverName VARCHAR(32) NULL,
  teamName1 VARCHAR(32) NULL,
  teamName2 VARCHAR(32) NULL,
  result VARCHAR(32) NULL,
  winningTime VARCHAR(32) NULL
);