CREATE TABLE IF NOT EXISTS login (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(32) NOT NULL,
  email VARCHAR(32) NOT NULL,
  password VARCHAR(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS football (
  id INT AUTO_INCREMENT PRIMARY KEY,
  league VARCHAR(32) NOT NULL,
  matchDate DATE,
  teamName1 VARCHAR(32) NOT NULL,
  teamName2 VARCHAR(32) NOT NULL,
  result VARCHAR(32) NULL
);

CREATE TABLE IF NOT EXISTS basketball (
  id INT AUTO_INCREMENT PRIMARY KEY,
  league VARCHAR(32) NOT NULL,
  matchDate DATE,
  teamName1 VARCHAR(32) NOT NULL,
  teamName2 VARCHAR(32) NOT NULL,
  result VARCHAR(32) NULL
);

CREATE TABLE IF NOT EXISTS motorsport (
  id INT AUTO_INCREMENT PRIMARY KEY,
  championship VARCHAR(32) NOT NULL,
  grandPrix VARCHAR(32) NOT NULL,
  raceDate DATE,
  driverName VARCHAR(32) NOT NULL,
  teamName VARCHAR(32) NOT NULL,
  winningTime VARCHAR(32) NULL
);